//import type { Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from '@/../../src/component/Navbar/page';



const monts = Montserrat({
  variable: "--font-monts",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${monts.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
